# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure(2) do |config|
        # - set the image to be used to be ubuntu/zesty64
        # - set the hostname of the machine
        # - do not check for base image updates
        # - do not sync the default vagrant directory
        config.vm.box = "ubuntu/zesty64"
        config.vm.hostname = "test-machine"
        config.vm.box_check_update = false
        config.vm.synced_folder ".", "/vagrant", disabled: true


        # - configure some parameters from the virtualbox provider
        config.vm.provider "virtualbox" do |v|
                v.memory = 512
                v.cpus = 1
        end


        # hook ansible into the process of provisioning
        # the machine.
        # -     using the ansible configuration file
        #       located at `../ansible/ansible.cfg`, 
        #       execute the playbook at `playbooks/provision-vagrant.yml`
        config.vm.provision "ansible" do |ansible|
                ansible.playbook = "../ansible/playbooks/provision-vagrant.yml"
                ansible.config_file = "../ansible/ansible.cfg"
        end
end
